---
name: Object-Factory-Declarative
version: 0.07
author:
  - 'Jim Schneider <perl@jrcsdevelopment.com>'
abstract: Create object factory methods using declarative syntax
license: perl
resources:
  license: http://dev.perl.org/licenses/
provides:
  Object::Factory::Declarative:
    file: lib/Object/Factory/Declarative.pm
    version: 0.07
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
