---
name: Object-Factory-Declarative
version: 0.04
author:
  - Jim Schneider <perl@jrcsdevelopment.com>
abstract: Create object factory methods using declarative syntax
license: perl
provides:
  Object::Factory::Declarative:
    file: lib/Object/Factory/Declarative.pm
    version: 0.04
generated_by: Module::Build version 0.2612
